apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keptn
spec:
  releaseName: keptn
  chart:
    spec:
      chart: keptn
      sourceRef:
        kind: HelmRepository
        name: keptn
        namespace: flux-system
      version: "0.18.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
