apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
spec:
  releaseName: karpenter
  chart:
    spec:
      chart: karpenter
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
      version: "0.13.2"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
