apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubecost
spec:
  releaseName: kubecost
  chart:
    spec:
      chart: cost-analyzer
      sourceRef:
        kind: HelmRepository
        name: kubecost
        namespace: flux-system
      version: "1.95.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
